# Generated by Django 5.2.8 on 2025-11-13 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_annotationbatch_batchitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_providers',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('enum', 'Enum'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20)),
                ('allowed_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attributes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='annotationbatch',
            name='batch_type',
            field=models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='human', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotationbatch',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.annotationbatch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_ai', 'Pending AI'), ('ai_running', 'AI Running'), ('ai_done', 'AI Done'), ('assigned', 'Assigned'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('qa_done', 'QA Done')], default='pending_ai', max_length=20),
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suggested_value', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.aiprovider')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
            ],
            options={
                'db_table': 'ai_suggestions',
                'unique_together': {('product', 'attribute', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='AIConsensus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consensus_value', models.TextField()),
                ('method', models.CharField(max_length=50)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
            ],
            options={
                'db_table': 'ai_consensus',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='FinalAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('final_value', models.TextField()),
                ('source', models.CharField(choices=[('ai', 'AI'), ('human', 'Human'), ('consensus', 'Consensus')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'final_attributes',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='HumanAnnotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('annotated_value', models.TextField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
                ('batch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.batchitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'human_annotations',
                'unique_together': {('product', 'attribute', 'annotator', 'batch_item')},
            },
        ),
    ]
