# Generated by Django 5.2.8 on 2025-11-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_aiprovider_attribute_annotationbatch_batch_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationbatch',
            name='parent_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_batches', to='products.annotationbatch'),
        ),
        migrations.AddField(
            model_name='finalattribute',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='humanannotation',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='humanannotation',
            name='previous_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_ai', 'Pending AI'), ('ai_running', 'AI Running'), ('ai_done', 'AI Done'), ('assigned', 'Assigned'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('qa_done', 'QA Done'), ('finalized', 'Finalized')], default='pending_ai', max_length=20),
        ),
    ]
