# Generated by Django 5.2.8 on 2025-11-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_annotationbatch_parent_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationbatch',
            name='parent_batch',
        ),
        migrations.AddField(
            model_name='annotationbatch',
            name='batch_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='annotationbatch',
            name='batch_type',
            field=models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_sku',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_ai', 'Pending AI'), ('ai_running', 'AI Running'), ('ai_done', 'AI Done'), ('assigned', 'Assigned to Annotator'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('finalized', 'Finalized')], default='pending_ai', max_length=20),
        ),
    ]
