# Generated by Django 5.2.8 on 2025-11-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_aiprocessingcontrol_missingvalueflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
