# Generated by Django 5.2.8 on 2025-11-26 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('subcategory', models.CharField(blank=True, max_length=80, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='products.attribute')),
            ],
            options={
                'db_table': 'category_attribute_mappings',
                'ordering': ['category', 'subcategory', 'attribute__name'],
                'indexes': [models.Index(fields=['category', 'subcategory'], name='category_at_categor_f0ba45_idx')],
                'unique_together': {('category', 'subcategory', 'attribute')},
            },
        ),
    ]
