# Generated by Django 5.2.8 on 2025-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categoryattributemapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAttributeMapping',
        ),
    ]
