# Generated by Django 5.2.8 on 2025-11-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bootstrap_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    SubCategory = apps.get_model('products', 'SubCategory')
    Product = apps.get_model('products', 'Product')
    Mapping = apps.get_model('products', 'CategoryAttributeMapping')

    def normalize(value):
        if not value:
            return None
        value = value.strip()
        return value or None

    category_cache = {}
    subcategory_cache = {}

    def get_category(name):
        name = normalize(name)
        if not name:
            return None
        if name not in category_cache:
            category_cache[name], _ = Category.objects.get_or_create(name=name)
        return category_cache[name]

    def get_subcategory(category, name):
        name = normalize(name)
        if not category or not name:
            return None
        cache_key = (category.id, name)
        if cache_key not in subcategory_cache:
            subcategory_cache[cache_key], _ = SubCategory.objects.get_or_create(
                category=category,
                name=name
            )
        return subcategory_cache[cache_key]

    for product in Product.objects.all():
        category = get_category(getattr(product, 'category_legacy', None))
        subcategory = get_subcategory(category, getattr(product, 'subcategory_legacy', None))
        Product.objects.filter(pk=product.pk).update(category=category, subcategory=subcategory)

    for mapping in Mapping.objects.all():
        category = get_category(getattr(mapping, 'category_legacy', None))
        subcategory = get_subcategory(category, getattr(mapping, 'subcategory_legacy', None))
        Mapping.objects.filter(pk=mapping.pk).update(category=category, subcategory=subcategory)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_categoryattributemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'db_table': 'subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AlterModelOptions(
            name='aiconsensus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='categoryattributemapping',
            options={'ordering': ['category__name', 'subcategory__name', 'attribute__name']},
        ),
        migrations.AlterModelOptions(
            name='finalattribute',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='categoryattributemapping',
            name='category_at_categor_f0ba45_idx',
        ),
        migrations.AlterUniqueTogether(
            name='aiconsensus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categoryattributemapping',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='finalattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='humanannotation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='missingvalueflag',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_legacy',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='subcategory_legacy',
        ),
        migrations.RenameField(
            model_name='categoryattributemapping',
            old_name='category',
            new_name='category_legacy',
        ),
        migrations.RenameField(
            model_name='categoryattributemapping',
            old_name='subcategory',
            new_name='subcategory_legacy',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='categoryattributemapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mappings', to='products.category'),
        ),
        migrations.AddField(
            model_name='categoryattributemapping',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mappings', to='products.subcategory'),
        ),
        migrations.RunPython(bootstrap_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='categoryattributemapping',
            name='category_legacy',
        ),
        migrations.RemoveField(
            model_name='categoryattributemapping',
            name='subcategory_legacy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_legacy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_legacy',
        ),
        migrations.AlterField(
            model_name='categoryattributemapping',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_mappings', to='products.category'),
        ),
        migrations.AddField(
            model_name='aiconsensus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconsensus',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='finalattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='finalattribute',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='annotationbatch',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='aiconsensus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'attribute'), name='unique_active_ai_consensus'),
        ),
        migrations.AddConstraint(
            model_name='finalattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'attribute'), name='unique_active_final_attribute'),
        ),
        migrations.AddConstraint(
            model_name='humanannotation',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_item__isnull', False)), fields=('product', 'attribute', 'annotator', 'batch_item'), name='unique_annotation_per_batch_item'),
        ),
        migrations.AddConstraint(
            model_name='missingvalueflag',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_item__isnull', False)), fields=('product', 'attribute', 'annotator', 'batch_item'), name='unique_flag_per_batch_item'),
        ),
        migrations.AddConstraint(
            model_name='categoryattributemapping',
            constraint=models.UniqueConstraint(fields=('category', 'subcategory', 'attribute'), name='unique_category_subcategory_attribute'),
        ),
        migrations.AddIndex(
            model_name='categoryattributemapping',
            index=models.Index(fields=['category', 'subcategory'], name='category_at_categor_d4de0b_idx'),
        ),
    ]
